# Generated by Django 4.2.2 on 2024-04-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchatdetails',
            name='user',
        ),
    ]
