# Generated by Django 4.2.2 on 2024-04-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposts',
            name='posted_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
