# Generated by Django 4.2.2 on 2024-04-29 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_delete_userchatdetails_userdetails_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchingprofiles',
            name='post',
        ),
    ]
