# Generated by Django 4.2.2 on 2024-04-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_userdetails_options_userdetails_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='password',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
