# Generated by Django 4.2.2 on 2024-04-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_userdetails_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phone',
            field=models.CharField(blank=True, default='1234567899', max_length=250, null=True),
        ),
    ]
