# Generated by Django 4.2.2 on 2024-05-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_userdislikedprofiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
